#! /usr/bin/python3

def read_number(line, index):
    number = 0
    while index < len(line) and line[index].isdigit():
        number = number * 10 + int(line[index])
        index += 1
    if index < len(line) and line[index] == '.':
        index += 1
        decimal = 0.1
        while index < len(line) and line[index].isdigit():
            number += int(line[index]) * decimal
            decimal /= 10
            index += 1
    token = {'type': 'NUMBER', 'number': number}
    return token, index

#Addition/Soustraction
def read_plus(line, index):
    token = {'type': 'PLUS'}
    return token, index + 1

def read_minus(line, index):
    token = {'type': 'MINUS'}
    return token, index + 1

#Multiplication/Division
def read_multiply(line, index):
    token = {'type': 'MULTIPLY'}
    return token, index + 1

def read_divide(line, index):
    token = {'type': 'DIVIDE'}
    return token, index + 1

#Parentheses
def read_lparen(line, index):
    token = {'type': 'LPAREN'}
    return token, index + 1

def read_rparen(line, index):
    token = {'type': 'RPAREN'}
    return token, index + 1
    
#Token
def tokenize(line):
    tokens = []
    index = 0
    while index < len(line):
        if line[index].isdigit():
            (token, index) = read_number(line, index)
        elif line[index] == '+':
            (token, index) = read_plus(line, index)
        elif line[index] == '-':
            (token, index) = read_minus(line, index)
        elif line[index] == '*':
            (token, index) = read_multiply(line, index)
        elif line[index] == '/':
            (token, index) = read_divide(line, index)
        elif line[index] == '(':
            (token, index) = read_lparen(line, index)
        elif line[index] == ')':
            (token, index) = read_rparen(line, index)
        else:
            print('Invalid character found: ' + line[index])
            exit(1)
        tokens.append(token)
    return tokens


def evaluate(tokens):
    #Parentheses
    index = 0
    while index < len(tokens):
        if tokens[index]['type'] == 'RPAREN':
            sub_expression = []
            left = index - 1
            while tokens[left]['type'] != 'LPAREN':
                sub_expression.insert(0, tokens[left])
                left -= 1

            value = evaluate(sub_expression)

            tokens[left] = {'type': 'NUMBER', 'number': value}

            while left + 1 < len(tokens) and left + 1 <= index:
                tokens.pop(left + 1)
                index -= 1
            index = 0
        else:
            index += 1
            
    #Multiplication/Division
    index = 0
    while index < len(tokens):
        if tokens[index]['type'] == 'MULTIPLY':
            if tokens[index - 1]['type'] != 'NUMBER' or tokens[index + 1]['type'] != 'NUMBER':
                print('Invalid syntax')
                return 0
            tokens[index - 1]['number'] *= tokens[index + 1]['number']
            tokens.pop(index)
            tokens.pop(index)
        elif tokens[index]['type'] == 'DIVIDE':
            if tokens[index - 1]['type'] != 'NUMBER' or tokens[index + 1]['type'] != 'NUMBER':
                print('Invalid syntax')
                return 0
            tokens[index - 1]['number'] /= tokens[index + 1]['number']
            tokens.pop(index)
            tokens.pop(index)
        else:
            index += 1

    #Addition/Soustraction
    answer = 0
    tokens.insert(0, {'type': 'PLUS'}) # Insert a dummy '+' token
    index = 1
    while index < len(tokens):
        if tokens[index]['type'] == 'NUMBER':
            if tokens[index - 1]['type'] == 'PLUS':
                answer += tokens[index]['number']
            elif tokens[index - 1]['type'] == 'MINUS':
                answer -= tokens[index]['number']
            else:
                print('Invalid syntax')
                exit(1)
        index += 1
    return answer
    

def test(line):
    tokens = tokenize(line)
    actual_answer = evaluate(tokens)
    expected_answer = eval(line)
    if abs(actual_answer - expected_answer) < 1e-8:
        print("PASS! (%s = %f)" % (line, expected_answer))
    else:
        print("FAIL! (%s should be %f but was %f)" % (line, expected_answer, actual_answer))


# Add more tests to this function :)
def run_test():
    print("==== Test started! ====")
    test("1+2")
    test("1.0+2.1-3")
    test("3.0+4*2-1/5")
    
    test("11.5-3.5")
    test("0+1")
    test("0.0+1.0")
    test("1.25+2.75")
    test("9.9-0.9")
    test("123")
    test("5-10")
    test("10-4/2")
    test("1.5*2")
    test("3.0+4*2-1/5")
    test("6*7*8")
    test("100/8/2")

    test("(3.0+4*(2-1))/5")
    test("(6)")
    test("(6+7)")
    test("(6+7)+8")
    test("6+(7+8)")
    test("(6+7)+(8+9)")
    test("(6*7)")
    test("(6-7)/(8+9)")
    test("8/(7+6)")
    print("==== Test finished! ====\n")

run_test()

while True:
    print('> ', end="")
    line = input()
    tokens = tokenize(line)
    answer = evaluate(tokens)
    print("answer = %f\n" % answer)
